use world;
drop database sampleDB;
create database sampleDB;
use sampleDB;
create table BusinessCard (Name varchar(255), Address varchar(255), Telephone varchar(255));
insert into BusinessCard values ('Bob', 'Seocho-dong 123', '123-4567');
insert into BusinessCard values ('Sam', 'Sindang-dong 456', '321-4321');
desc BusinessCard;
drop table BusinessCard;
alter table BusinessCard add column id int;
alter table BusinessCard change Address Address1 varchar(255);
alter table BusinessCard modify Address1 char(255);
alter table BusinessCard add primary key(id);
alter table BusinessCard add unique(id);
alter table BusinessCard alter Address1 set default 'Seoul';
alter table BusinessCard rename BusinessCards;
desc BusinessCards;
alter table BusinessCards rename BusinessCard;
truncate table BusinessCard;
select * from BusinessCard;
drop table BusinessCard;
drop database sampleDB;
create database sampleDB;
use sampleDB;
create table BusinessCard (Name varchar(255), Address varchar(255), Telephone varchar(255));
desc BusinessCard;
insert into BusinessCard values ('Bob', 'Seoul', '123-4567');
insert into BusinessCard values ('Sam', 'Busan', '321-4567');
select * from BusinessCard;
alter table BusinessCard add column ID int;
alter table BusinessCard change Address Address1 varchar(255);
alter table BusinessCard modify Address1 char(255);
update BusinessCard set ID = 1 where Name = 'Bob';
update BusinessCard set ID = 2 where Name = 'Sam';
alter table BusinessCard add primary key(ID);
alter table BusinessCard add unique(ID);
alter table BusinessCard alter Address1 set default 'Seoul';
alter table BusinessCard rename BusinessCards;
desc BusinessCards;
show tables;
select * from BusinessCards;
truncate table BusinessCards;
drop table BusinessCards;
drop database sampleDB;
show databases;

